# Generated by Django 2.1.5 on 2021-08-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phone_number',
            new_name='subject',
        ),
    ]
